FROM node:23.8-alpine3.21 AS base
RUN npm i -g yarn --force

FROM base AS development
WORKDIR /app
EXPOSE 3000
ENTRYPOINT ["/bin/sh", "-c", "yarn install && yarn dev"]

FROM base AS build
WORKDIR /app
COPY package.json yarn.lock* ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

FROM node:23.8-alpine3.21 AS production
WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app/package.json /app/yarn.lock* ./
RUN yarn install --production --frozen-lockfile
COPY --from=build /app/dist ./dist

EXPOSE 5000
CMD ["node", "dist/server.js"]
